import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

type LeaderboardEntry = {
  id: number;
  username: string;
  score: number;
  category: string;
  level: number;
  created_at: string;
};

type ScorePayload = {
  username: string;
  score: number;
  category: string;
  level: number;
};

const sanitizeName = (name: string): string => name.trim().replace(/\s+/g, " ").slice(0, 24);

const getSupabase = () => {
  // Setup:
  // 1) Create a Supabase project at https://supabase.com
  // 2) In SQL Editor run:
  //    create table if not exists public.scores (
  //      id bigint generated by default as identity primary key,
  //      username text not null,
  //      score int not null,
  //      category text not null,
  //      level int not null,
  //      created_at timestamptz not null default now()
  //    );
  // 3) Add env vars in `.env.local`:
  //    NEXT_PUBLIC_SUPABASE_URL=your_project_url
  //    SUPABASE_SERVICE_ROLE_KEY=your_service_role_key
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceKey) {
    return null;
  }
  return createClient(url, serviceKey, { auth: { persistSession: false } });
};

const sanitizePayload = (payload: Partial<ScorePayload>): ScorePayload | null => {
  const username = typeof payload.username === "string" ? sanitizeName(payload.username) : "";
  const category = typeof payload.category === "string" ? payload.category.trim().slice(0, 40) : "";
  const level = Math.max(1, Math.floor(Number(payload.level ?? 1)));
  const score = Math.max(0, Math.floor(Number(payload.score ?? 0)));
  if (!username || !category) return null;
  return { username, score, category, level };
};

export async function GET() {
  const supabase = getSupabase();
  if (!supabase) {
    return NextResponse.json({ error: "Supabase is not configured.", entries: [] }, { status: 500 });
  }
  const { data, error } = await supabase
    .from("scores")
    .select("id, username, score, category, level, created_at")
    .order("score", { ascending: false })
    .order("created_at", { ascending: true })
    .limit(10);

  if (error) {
    return NextResponse.json({ error: "Could not load leaderboard.", entries: [] }, { status: 500 });
  }
  return NextResponse.json({ entries: (data ?? []) as LeaderboardEntry[] });
}

export async function POST(request: Request) {
  const supabase = getSupabase();
  if (!supabase) {
    return NextResponse.json({ error: "Supabase is not configured.", entries: [] }, { status: 500 });
  }

  const body = (await request.json()) as Partial<ScorePayload>;
  const entry = sanitizePayload(body);
  if (!entry) {
    return NextResponse.json({ error: "Invalid score payload." }, { status: 400 });
  }

  const { error: insertError } = await supabase.from("scores").insert(entry);
  if (insertError) {
    return NextResponse.json({ error: "Could not submit score." }, { status: 500 });
  }

  const { data, error } = await supabase
    .from("scores")
    .select("id, username, score, category, level, created_at")
    .order("score", { ascending: false })
    .order("created_at", { ascending: true })
    .limit(10);

  if (error) {
    return NextResponse.json({ error: "Could not load leaderboard." }, { status: 500 });
  }
  return NextResponse.json({ entries: (data ?? []) as LeaderboardEntry[] });
}
