import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

type LeaderboardEntry = {
  id: number;
  username: string;
  score: number;
  category: string;
  level: number;
  created_at: string;
};

type ScorePayload = {
  username: string;
  score: number;
  category: string;
  level: number;
};

const sanitizeName = (name: string): string => name.trim().replace(/\s+/g, " ").slice(0, 24);

const getSupabase = () => {
  // Setup:
  // 1) Create a Supabase project at https://supabase.com
  // 2) In SQL Editor run:
  //    create table if not exists public.scores (
  //      id bigint generated by default as identity primary key,
  //      username text not null,
  //      score int not null,
  //      category text not null,
  //      level int not null,
  //      created_at timestamptz not null default now()
  //    );
  // 3) Add env vars in `.env.local`:
  //    NEXT_PUBLIC_SUPABASE_URL=your_project_url
  //    NEXT_PUBLIC_SUPABASE_ANON_KEY=your_project_anon_key
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !anonKey) {
    return null;
  }
  return createClient(url, anonKey, { auth: { persistSession: false } });
};

const sanitizePayload = (payload: Partial<ScorePayload>): ScorePayload | null => {
  const username = typeof payload.username === "string" ? sanitizeName(payload.username) : "";
  const category = typeof payload.category === "string" ? payload.category.trim().slice(0, 40) : "";
  const level = Math.max(1, Math.floor(Number(payload.level ?? 1)));
  const score = Math.max(0, Math.floor(Number(payload.score ?? 0)));
  if (!username || !category) return null;
  return { username, score, category, level };
};

const mapBestScoresByPlayer = (rows: LeaderboardEntry[]): LeaderboardEntry[] => {
  const byUser = new Map<string, LeaderboardEntry>();
  rows.forEach((row) => {
    const existing = byUser.get(row.username);
    if (!existing) {
      byUser.set(row.username, row);
      return;
    }
    const rowTime = new Date(row.created_at).getTime();
    const existingTime = new Date(existing.created_at).getTime();
    if (row.score > existing.score || (row.score === existing.score && rowTime > existingTime)) {
      byUser.set(row.username, row);
    }
  });
  return [...byUser.values()].sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    return new Date(a.created_at).getTime() - new Date(b.created_at).getTime();
  });
};

export async function GET() {
  const supabase = getSupabase();
  if (!supabase) {
    return NextResponse.json({ error: "Supabase is not configured.", entries: [] }, { status: 500 });
  }
  const { data, error } = await supabase
    .from("scores")
    .select("id, username, score, category, level, created_at")
    .order("score", { ascending: false })
    .order("created_at", { ascending: true });

  if (error) {
    return NextResponse.json({ error: "Could not load leaderboard.", entries: [] }, { status: 500 });
  }
  return NextResponse.json({ entries: mapBestScoresByPlayer((data ?? []) as LeaderboardEntry[]) });
}

export async function POST(request: Request) {
  const supabase = getSupabase();
  if (!supabase) {
    return NextResponse.json({ error: "Supabase is not configured.", entries: [] }, { status: 500 });
  }

  const body = (await request.json()) as Partial<ScorePayload>;
  const entry = sanitizePayload(body);
  if (!entry) {
    return NextResponse.json({ error: "Invalid score payload." }, { status: 400 });
  }

  const { error: insertError } = await supabase.from("scores").insert(entry);
  if (insertError) {
    return NextResponse.json({ error: "Could not submit score." }, { status: 500 });
  }

  const { data, error } = await supabase
    .from("scores")
    .select("id, username, score, category, level, created_at")
    .order("score", { ascending: false })
    .order("created_at", { ascending: true });

  if (error) {
    return NextResponse.json({ error: "Could not load leaderboard." }, { status: 500 });
  }
  return NextResponse.json({ entries: mapBestScoresByPlayer((data ?? []) as LeaderboardEntry[]) });
}
